# Generated by Django 6.0.2 on 2026-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_services_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name": "услуга", "verbose_name_plural": "услуги"},
        ),
    ]
