# Generated by Django 6.0.2 on 2026-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_lead_contracts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "verbose_name": "потенциальный клиент",
                "verbose_name_plural": "потенциальные клиенты",
            },
        ),
    ]
