# Generated by Django 6.0.2 on 2026-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customers",
            options={
                "verbose_name": "активный клиент",
                "verbose_name_plural": "активные клиенты",
            },
        ),
    ]
