# Generated by Django 6.0.2 on 2026-04-23 17:07

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0002_services_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contracts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "file_doc",
                    models.FileField(
                        upload_to="contracts/%Y/%m/%d/", verbose_name="Файл контракта"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime(
                            2026, 4, 23, 17, 7, 9, 712831, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата заключения",
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Окончание действия")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="services.services",
                        verbose_name="Услуга",
                    ),
                ),
            ],
        ),
    ]
