# Generated by Django 6.0.2 on 2026-04-27 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contracts_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата заключения'),
        ),
    ]
