# Generated by Django 6.0.2 on 2026-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_alter_contracts_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contracts",
            options={"verbose_name": "контракт", "verbose_name_plural": "контракты"},
        ),
    ]
