"""
Django settings for crm project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

load_dotenv(dotenv_path=".env.app")
load_dotenv(dotenv_path=".env.db", override=True)


BASE_DIR = Path(__file__).resolve().parent.parent

# Булевый флаг, определяющий, выполняется ли код в среде GitHub Actions.
# Значение True устанавливается при запуске workflow GitHub Actions,
# в остальных случаях значение равно False.
# IS_CI = os.environ.get("GITHUB_ACTIONS") == "true"

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "").split(",") if host.strip()]

# Настройка URL страницы входа и URL перенаправления пользователя после успешной аутентификации.
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "login"

# Настройки безопасности.
if DEBUG != True:
    # Открывать сайт только по HTTPS в течение указанного периода.
    SECURE_HSTS_SECONDS = 3600
    # Распространяет HSTS на все поддомены, только если все поддомены также поддерживают HTTPS.
    # Если у домена нет поддоменов, практической пользы нет.
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Для включения в HSTS preload list
    # SECURE_HSTS_PRELOAD = True
    # Перенаправляет HTTP-запросы на HTTPS.
    SECURE_SSL_REDIRECT = True
    # Полностью запрещает отображение страниц в iframe.
    X_FRAME_OPTIONS = "DENY"
    # Для проксирующих серверов (nginx и др.)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Разрешает передавать cookie сессии только по HTTPS.
    SESSION_COOKIE_SECURE = True
    # Разрешает передавать CSRF-cookie только по HTTPS.
    CSRF_COOKIE_SECURE = True
    # Дополнительные настройки cookies
    SESSION_COOKIE_HTTPONLY = True  # Защита от XSS
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'  # Защита от CSRF
    CSRF_COOKIE_SAMESITE = 'Lax'


INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "src.clients.apps.ClientsConfig",
    "src.services.apps.ServicesConfig",
    "src.ad_campaign.apps.AdCampaignConfig",
    "src.contracts.apps.ContractsConfig",
    "src.customers.apps.CustomersConfig",
    "src.users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crm.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        env="DATABASE_URL", default="sqlite:///db.sqlite3"
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "dist/static")

MEDIA_URL = "/media/"
MEDIA_ROOT = "/app/media"

# LOGLEVEL = os.getenv("LOGLEVEL", "info").upper()

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "%(asctime)s [%(name)s:%(levelname)s]: %(message)s",
#             "datefmt": "%Y-%m-%d %H:%M:%S",
#         },
#     },
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },
#         "null": {
#             "class": "logging.NullHandler",
#         },
#         # "file": {
#         #     "class": "logging.handlers.RotatingFileHandler",
#         #     "filename": BASE_DIR / "logs/app.log",
#         #     "maxBytes": 1024 * 1024 * 5,
#         #     "backupCount": 3,
#         #     "formatter": "verbose",
#         # },
#         # 'loki': {
#         #     'class': 'python_loki.LokiHandler',
#         #     'url': os.getenv('LOKI_ENDPOINT'),
#         #     'tags': {'application': 'crm_backend'},
#         #     'version': '1',
#         # },
#     },
#     "root": {
#         "handlers": ["console"],
#         "level": LOGLEVEL,
#     },
#     "loggers": {
#         # "log_file": {
#         #     "handlers": ["file"],
#         #     "level": LOGLEVEL,
#         #     "propagate": True,
#         # },
#         "ci": {
#             "handlers": ["console"],
#             "level": LOGLEVEL,
#             "propagate": False,
#         },
#         "django.request": {
#             "handlers": ["null"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#         # 'log_loki': {
#         #     'handlers': ['loki'],
#         #     'level': LOGLEVEL,
#         #     'propagate': True,
#         # }
#     },
# }
