# Generated by Django 6.0.2 on 2026-05-05 16:30

from django.db import migrations


groups_data = {
    "Admins": ["view_user", "change_user", "add_user", "delete_user"],
    "Marketing": [
        "add_services",
        "change_services",
        "delete_services",
        "view_services",
        "add_advertisement",
        "change_advertisement",
        "delete_advertisement",
        "view_advertisement",
    ],
    "Operators": ["add_lead", "change_lead", "delete_lead", "view_lead"],
    "Managers": [
        "add_contracts",
        "change_contracts",
        "delete_contracts",
        "view_contracts",
        "view_lead",
        "add_customers",
        "change_customers",
        "delete_customers",
        "view_customers",
    ],
}


def create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group_name, perms_codenames in groups_data.items():
        group, _ = Group.objects.get_or_create(name=group_name)

        for codename in perms_codenames:
            perm = Permission.objects.get(codename=codename)
            group.permissions.add(perm)


def reverse_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in groups_data.keys():
        Group.objects.filter(name=name).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_alter_contracts_start_date"),
    ]

    operations = [migrations.RunPython(create_groups, reverse_groups)]
