# Generated by Django 6.0.2 on 2026-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ad_campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "verbose_name": "рекламная кампания",
                "verbose_name_plural": "рекламные кампании",
            },
        ),
    ]
