# Generated by Django 6.0.2 on 2026-08-12 19:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ad_campaign", "0002_alter_advertisement_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Бюджет",
            ),
        ),
    ]
